# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
gems: [jekyll-paginate, jekyll-sitemap]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://webdev.techmill.co
baseurl: ""
title: The Bolter
author: TechMill Denton
description: A free crash course into web development.
avatar: profile.png

email: info@techmilldenton.com
facebook: techmilldenton
github: techmilldenton # username
twitter: techmilldenton

#Comment out if you don't want disqus 
disqus: techmill
google_analytics: UA-51772036-5

# Collections
collections:
  homework:
    output: true
    permalink: /:collection/:name

# needed for travis-ci build
exclude: [vendor]
