# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://webdev.techmill.co
baseurl: ""
title: The Bolter
author: TechMill Denton
description: A free crash course into web development.
avatar: profile.png
email: info@techmilldenton.com
github: techmilldenton # username
twitter: techmilldenton
#Comment out if you don't want disqus 
disqus: techmill
google_analytics: UA-51772036-5


# needed for travis-ci build
exclude: [vendor]
